### ISSUE TITLE
Support for large files in multipart

### ISSUE THREAD

**Issue by cjstehno** [http-builder-ng/http-builder-ng#132]
We had a question come up on [StackOverflow](https://stackoverflow.com/questions/44502619/httpbuilder-ng-multipart-form-data-with-large-application-zip-part) about support for large files in multipart requests. The error seems to be based on a file size limit imposed by the Apache client; however, it would be good to have a strategy around supporting this use case noted in the documentation (across all three clients).

Watch the SO thread for any updates.

**Comment by cjstehno** [comment]
This should be possible now by modifying the client config directly.

**Comment by cjstehno** [comment]
Didn't mean to close this - still want to document it in usage examples.

**Comment by PrzemekCh** [comment]
Hi @cjstehno,
"This should be possible now by modifying the client config directly."
Where can I find some examples?

**Comment by cjstehno** [comment]
You'd have to use the specific configuation for your underlying client implementation. If you come up with a specific example please share and I'll add it to the user guide.

**Comment by mengjiann** [comment]
I have tried with both ApacheHttpBuilder and OkHttpBuilder implementation for performing a post multipart upload with more than 1G. But, i'm getting out of memory issue for both implementation.
For OkHttpBuilder and ApacheHttpBuilder, it is caused by `IoUtils.streamToBytes(inputStream)`  in the ToServer implementation.
