### ISSUE TITLE
Handlers for `failure` and `success` have empty streams

### ISSUE THREAD

**Issue by cjstehno** [http-builder-ng/http-builder-ng#138]
In the `failure` and `success` response handlers you can get the body content using the second parameter of the handler; however, the `InputStream` and `Reader` are empty - it seems like these should also be viable means of accessing the body content. 

Whatever comes of this investigation, be sure to update the documentation to be more clear about the intended use cases for each.

**Comment by dwclark** [comment]
failure/success/when are called after the content-type specific handlers have been called. The handling of success/failure is orthogonal to the handling of the content itself. The content-type specific handlers are the ones that need access to the input stream so the streams will be open during content-type specific handling.

In general I don't think any of the handlers should be responsible for opening or closing streams. The core builders need to guarantee that stream management happens properly and that they are closed correctly, guaranteed.

Users of http-builder-ng should follow these bits of advice:

* **If you want to deal with parsed content, do that in a success/failure/when handler** This is probably what you want to do 99% of the time as a user of http-builder-ng. Being able to easily consume content as pre-parsed objects is one of the main selling points of http-builder-ng
* **If you want to deal with the data streams, do that by implementing a content parser** You can use either the input stream or the reader inside the FromServer interface (but not both). There is no need to worry about managing opening or closing the stream, the builders will do the right thing. You are also free to duplicate or "tee" the stream or reader and delegate to existing parsers.
* **If you want to do something out of band (such as logging or adding metrics), use an interceptor** This is fairly easy to do because neither what is requested nor what is returned is changed by the interceptor.
* **If you want to change what is requested (before being sent) or change the object(s) returned from the content parser use an interceptor** This is probably the most difficult to do because the order of interceptor invocation is not guaranteed but the interceptor must still return to the user what is expected. If the user is expecting a List<String> then the interceptor must make sure that the user gets that.
* **If you want to handle unexepected exceptions, implement an exception handler.** See HttpConfig.Response.exception for details.

**Comment by cjstehno** [comment]
Gotcha. I have had a few asks related to this stuff. I will add this content in some form to the user guide and java docs to hopefully help clear things up. Thanks for the write-up.

Note to self: also make sure that all the handlers mentioned have all of their parameters documented.

**Comment by cjstehno** [comment]
Applied this info to the docs.
