### ISSUE TITLE
docs refer to nonexistent groovyx.net.http.CoreEncoders::multipart

### ISSUE THREAD

**Issue by kgeis** [http-builder-ng/http-builder-ng#179]
The documents refer to ways to do multipart encoding using -core. The corresponding classes do not exist in current JavaDoc.

**Comment by cjstehno** [comment]
Please add link to page you are looking at. The multipart encoders are there somewhere. Im just not sure what the context is.

**Comment by kgeis** [comment]
https://http-builder-ng.github.io/http-builder-ng/asciidoc/html5/#_multipart
https://github.com/http-builder-ng/http-builder-ng/blob/gh-pages/asciidoc/html5/configuration.html

The client-specific multipart encoders are in the Javadoc, but not the generic MultipartEncoder:
https://http-builder-ng.github.io/http-builder-ng/docs/javadoc/

**Comment by cjstehno** [comment]
Doh! It does exist and I found it (https://github.com/http-builder-ng/http-builder-ng/blob/master/http-builder-ng-core/src/test/groovy/groovyx/net/http/CoreEncoders.java) - It seems that for some reason it ended up in the `src/test` root rather than the `src/main` root. :-/

I will move the class to its proper location and cut a release, but it probably won't drop before Friday morning.

**Comment by cjstehno** [comment]
This has been fixed and will be released in 1.0.2 (today).
