### ISSUE TITLE
Allow relative paths.

### ISSUE THREAD

**Issue by TobiX** [http-builder-ng/http-builder-ng#182]
The original http-builder had the ability to use relative paths, something like this:

```groovy
HttpBuilder.configure {
  request.uri = 'http://localhost/foo/'
}.get {
  request.uri = 'bar'
}
```

would send a request to `http://localhost/foo/bar` - I tried to integrate something like that into `UriBuilder`, but I'm not quite sure how to make it work correctly with all that special path handling...

**Comment by cjstehno** [comment]
I have a fix for this which will be in today's release; however, the syntax would be:

```groovy
HttpBuilder.configure {
    request.uri = 'http://localhost/foo'
}.get { 
    request.path = 'something/more'
}
```

Notice `path` rather than `uri` in the `get` closure. The `uri` property is meant for setting the whole thing, while the `path` is for the path part. With the fix, a `path` specified without a leading `/` will be appended to the existing path "/foo" in this case, rather than overwriting it.
