### ISSUE TITLE
HTTP2 support

### ISSUE THREAD

**Issue by aalmiray** [http-builder-ng/http-builder-ng#41]
Would it be possible to split the codebase to support HTTP2 via http://square.github.io/okhttp/ ?

**Comment by cjstehno** [comment]
Not sure what you mean by splitting the code base, but we could add support for OkHttp as one of the underlying client libraries if that's what you mean.

**Comment by aalmiray** [comment]
Well IIRC the "old" http-builder has a strict dependency to Apache HttpComponents. I see that this build has setup http-components in `compileOnly` scope which means that it still depends on that library in some way.

**Comment by dwclark** [comment]
We depend on Apache Http Client only for compilation, by default the apache libraries are not pulled in and not used.

A co-worker and I were discussing OkHttp yesterday since we use it on some projects and I had started looking into making http-builder-ng support OkHttp. It looked pretty straightforward.

We may want to think about making subprojects for using http-builder-ng with different libraries. Using this approach users would declare dependencies on http-builder-ng-apache or http-builder-ng-okhttp which would then automatically pull in the correct libraries. Plain vanilla http-builder-ng would use Java HttpURLConnection just like it does now.

**Comment by cjstehno** [comment]
@dwclark Funny, I was just thinking the same thing after reading this issue this morning - the sub-projects would be pretty small, but makes sense to split things up. Let me know if this is something you are going to work on - if not, I can probably split out the current implementations over the long weekend.

**Comment by dwclark** [comment]
@cjstehno I'm still busy prepping for G3, so I won't have time to do this until a week from Friday at the earliest. Go ahead and do the split. We should bump to 0.11.0. Hopefully after the split, adding OkHttp, and (maybe) doing multipart support it's time for a 1.0 release.

**Comment by cjstehno** [comment]
The Apache implementation has been broken out into a sub-project sibling of the core codebase (v0.11.0). I want to refactor the unit testing a bit to reduce duplication and make it easier to test alternate implementations (see #51) then I will try to take this one up.

**Comment by cjstehno** [comment]
@dwclark I am working on implementing this and have it mostly code complete. I am on the fence about whether this should be version `0.12.0` or `0.11.1` - it _is_ a new feature, so generally I would lean towards `12`; however, since we are pre-1.0 and this is a purely additive feature I could also see a simple sub-release (e.g. `0.11.1`)... any thoughts?

**Comment by dwclark** [comment]
Since it's additive and doesn't break anything, make it 0.11.1. The 0.11 release was mainly to support this anyway.

**Comment by dwclark** [comment]
Shouldn't this line:

https://github.com/http-builder-ng/http-builder-ng/blob/dev-ok-http/http-builder-ng-okhttp/src/main/java/groovyx/net/http/OkHttpBuilder.java#L117

and this one

https://github.com/http-builder-ng/http-builder-ng/blob/dev-ok-http/http-builder-ng-okhttp/src/main/java/groovyx/net/http/OkHttpBuilder.java#L145

Use the actual content type from the request config and not assume 'text/html'?

**Comment by dwclark** [comment]
OK nevermind, I guess it is a default setting if we don't specify a body.

**Comment by dwclark** [comment]
@cjstehno Looks good so far. It looks like you were able to implement it without too much effort. Hooray on getting the interfaces correct.

**Comment by cjstehno** [comment]
`OkHttp` support has been added - see the `0.11.1` release (now in master and published). There is some lag when creating new repos on Bintray so the `okhttp` library might not be available on Jcenter for a few hours. See the README for a work-around if you need it sooner.
