### ISSUE TITLE
Request Headers

### ISSUE THREAD

**Issue by gregorydickson** [http-builder-ng/http-builder-ng#94]
I am digging through the source, already tried the examples, trying to add custom request headers, I will probably find it but would be nice to be in the documentation. Thanks!!

**Comment by cjstehno** [comment]
Good call... I will see what we can come up with. 

@dwclark since you wrote the header stuff, can you shoot me a quick example of creating a custom header (or just post it here) and I will add it to the user guide. I will try to take a look at it myself in a day or two but it's been a while since I thought about the headers and I remember they were a bit tricky. :-/

**Comment by gregorydickson** [comment]
FYI, this worked:

def http = HttpBuilder.configure {}
http.post {
			request.headers['Authorization'] = token
    		      
		}

**Comment by cjstehno** [comment]
Oh, yeah, sorry, I thought you were trying to create one of the multi-value headers. Yes, that would be the correct way to do simple headers. I will make sure that is in the documentation.

**Comment by cjstehno** [comment]
I have added some documentation about this in the User Guide for the next release. (`development` branch)
